[[filesystem-config-source]]
== FileSystem Config Source

Creates a ConfigSource that will look into a directory where each file corresponds to a property (the file name is
the property key and its textual content is the property value).

For example, if a directory structure looks like:

[source]
----
conf
|__foo/
   |__num.max
   |__num.size
|__bar/
   |__str.val
----

A `new FileSystemConfigSource("conf/foo")` will provide 2 properties:

* num.max
* num.size

And their values is the file content.

Wildcard locations at last path segment also supported. A `new FileSystemConfigSource("conf/*/")` will provide 3
properties:

* num.max
* num.size
* str.val

Nested directories are not supported.

This Config Source can be used to read configuration from
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap[Kubernetes ConfigMap]. Check the
https://github.com/smallrye/smallrye-config/blob/main/examples/configmap/README.adoc[Kubernetes ConfigMap ConfigSource Example].

The same mapping rules as defined for environment variables are applied, so the FileSystemConfigSource will search for a given property name (e.g. com.ACME.size):

* Exact match (i.e. com.ACME.size)
* Replace each character that is neither alphanumeric nor _ with _ (i.e. com_ACME_size)
* Replace each character that is neither alphanumeric nor _ with _; then convert the name to upper case (i.e. COM_ACME_SIZE)

=== Usage

To use the FileSystem Config Source, add the following to your Maven `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>io.smallrye.config</groupId>
    <artifactId>smallrye-config-source-file-system</artifactId>
    <version>{version}</version>
</dependency>
----

This Config Source register itself with the application if the dependency is present. Use the configuration property
`smallrye.config.source.file.locations` to set the directory paths to lookup additional configurations.
It accepts multiple locations separated by a comma and each must represent a valid URI to a directory.
