[[indexed-properties]]
== Indexed Properties

In Microprofile Config, a config value which contains unescaped commas may be converted to `Collection`. This works
for simple cases, but it becomes cumbersome and limited for more advanced cases.

Indexed Properties provide a way to use indexes in config property names to map specific elements in a `Collection`
type. Since the indexed element is part of the property name and not contained in the value, this can also be used to
map complex object types as `Collection` elements. Consider:

[source,properties]
----
# MicroProfile Config - Collection Values
my.collection=dog,cat,turtle

# SmallRye Config - Indexed Property
my.indexed.collection[0]=dog
my.indexed.collection[1]=cat
my.indexed.collection[2]=turtle
----

The indexed property syntax uses the property name and square brackets with an index in between.

A call to `Config#getValues("my.collection", String.class)`, will automatically create and convert a `List<String>`
that contains the values `dog`, `cat` and `turtle`. A call to `Config#getValues("my.indexed.collection", String.class)`
returns the exact same result. For compatibility reasons, if SmallRye Config finds the same property name in their
indexed and unindexed format, the unindexed value takes priority.

The indexed property is sorted by their index before being added to the target `Collection`. Any gaps contained in the
indexes do not resolve to the target `Collection`, which means that the `Collection` result will store all values in a
continued fashion and without gaps.
