[[locations]]
== Locations

Additionally, to the default config locations specified by the MicroProfile Config specification, SmallRye Config
provides a way to scan additional locations for configuration properties files.

The `smallrye.config.locations` configuration property accepts multiple locations separated by a comma and each must
represent a valid `URI`. The supported `URI` schemes are:

* file or directory
* classpath resource
* jar resource
* http resource

Each `URI` scheme loads any discovered properties file in a `ConfigSource`. Discovered sources are then sorted with the
`config_ordinal` property if present. If all sources have the same ordinal, they are sorted by the order in which they
were found.

If a profile is active, the profile resource is only loaded if t he unprofiled resource is available in the same
location. This is to keep a consistent loading order and match with the unprofiled resource. Profiles are not
taken into account if the location is a directory.

=== Examples

==== All properties files from a directory:
`smallrye.config.locations=./src/main/resources/`
`smallrye.config.locations=/user/local/config`

==== All `additional.properties` files from the classpath:
`smallrye.config.locations=additional.properties`

==== The `resources.properties` file from a specific jar:
`smallrye.config.locations=jar:file:///user/local/app/lib/resources-.jar!/resources.properties`

==== The `config.properties` file from a web server:
`smallrye.config.locations=http://localhost:8080/config/config`.
