[[profiles]]
== Profiles

SmallRye Config supports multiple configurations with the same name and selects them via a profile property.

To be able to set properties with the same name, each property needs to be prefixed with a percentage sign `%` followed
by the profile name and a dot `.` in the syntax `%{profile-name}.config.name`:

[source,properties]
----
# Regular property
my.prop=1234
# Profile property
%dev.my.prop=5678
----

To use the profile `dev`, the configuration `smallrye.config.profile=dev` has to be set into any valid ConfigSource.

Any lookup to the `my.prop` configuration name will first search by the active profile name `%dev.my.prop` and then
fallback to `my.prop` if no value is present.

When looking up the property `my.prop` with the `dev` profile active the value is `5678`.

=== Ordinals

Profile lookups are only valid if the `ConfigSource` has a higher ordinal than a lookup to the regular configuration
name. Consider:

[source,properties]
----
# Source main.properties
config_ordinal=1000
# Regular property
my.prop=1234
----

[source,properties]
----
# Source profile.properties
config_ordinal=100
# Regular property
%dev.my.prop=5678
----

Even with the profile `dev` active, the lookup value for `my.prop` is `1234`. This prevents lower ordinal sources to
set a profile property value that cannot be overridden unless the profile property is also overridden.

=== Multiple Profiles

Multiple Profiles may be active at the same time. The configuration `smallrye.config.profile` accepts a comma-separated
list of profile names: `smallrye.config.profile=common,dev`. Both `common` and `dev` are separate profiles.

When multiple profiles are active, the rules for profile configuration are exactly the same. If two profiles define the
same configuration, then the last listed profile has priority. Consider:

[source,properties]
----
smallrye.config.profile=common,dev

my.prop=1234
%common.my.prop=0
%dev.my.prop=5678

%common.commom.prop=common
%dev.dev.prop=dev
%test.test.prop=test
----

Then

* `common.prop` value is `common`
* `dev.prop` value is `dev`
* `my.prop` value is `5678`
* `test.prop` does not have a value

=== Parent Profile

A Parent Profile adds one level of hierarchy to the current profile. The configuration `smallrye.config.profile.parent`
accepts a single profile name.

When the Parent Profile is active, if a property cannot be found in the current active Profile, the config lookup
fallbacks to the Parent Profile. Consider:

[source,properties]
----
smallrye.config.profile=dev
smallrye.config.profile.parent=common

my.prop=1234
%common.my.prop=0
%dev.my.prop=5678

%common.commom.prop=common
%dev.dev.prop=dev
%test.test.prop=test
----

Then

* `common.prop` value is `common`
* `dev.prop` value is `dev`
* `my.prop` value is `0`
* `test.prop` does not have a value
