[[secret-keys]]
== Secret Keys

When configuration properties contain passwords or other kinds of secrets, Smallrye Config can hide them to
prevent accidental exposure of such values.

**This is no way a replacement for securing secrets. ** Proper security mechanisms must still be used to secure
secrets. However, there is still the basic problem that passwords and secrets are generally encoded simply as
strings.

Secret Keys provides a way to "lock" the configuration so that secrets do not appear unless explicitly enabled.

=== Configuration

Secret Keys requires the list of Config property names that must be hidden. This can be supplied in
`SmallRyeConfigBuilder#withSecretKeys` and initialized with `SmallRyeConfigFactory`. From this point forward, any
config name retrieved from the `Config` instance that matches the Secret Keys will throw a `SecurityException`.

Secret Keys is implemented by a SmallRye Config interceptor, so it order for it to work, the
`SecretKeysConfigSourceInterceptor` needs to be added to the Config, either by registering the interceptor alone, or
by registing the default interceptors via `SmallRyeConfigBuilder.withSecretKeys#addDefaultInterceptors`.

=== Unlock Keys

Access to the Secret Keys, is available via the APIs `io.smallrye.config.SecretKeys#doUnlocked(java.lang.Runnable)` and
`io.smallrye.config.SecretKeys#doUnlocked(java.util.function.Supplier<T>)`.

[source,java]
----
String secretValue = SecretKeys.doUnlocked(() -> {
    config.getValue("secret", String.class);
});
----

Secret Keyes are only unlocked in the context of `doUnlocked`. Once the execution completes, the secrets become
locked again.
