[[index]]
= SmallRye Config Documentation
:ext-relative: {outfilesuffix}
:toc!:

Welcome to the Documentation for SmallRye Config.

SmallRye Config is an implementation of https://github.com/eclipse/microprofile-config/[Eclipse MicroProfile Config].

== Extensions

In addition to the features provided by MicroProfile Config, smallrye-config provides the following extensions.

=== Config Sources

* https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/PropertiesConfigSource.java[PropertiesConfigSource]
 creates a ConfigSource from a Java `Properties` or `Map<String, String>` objects or a properties file (referenced by its URL).
* https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/DirConfigSource.java[DirConfigSource]
 creates a ConfigSource that will look into a directory where each file corresponds to a property (the file name is the property key and its textual content is the property value).
 This ConfigSource can be used to read configuration from https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap[Kubernetes ConfigMap].
* https://github.com/smallrye/smallrye-config/tree/master/sources/zookeeper[ZkMicroProfileConfig] creates a ConfigSource that is backed by Apache Zookeeper

[[more-resources]]
== More Resources

* https://github.com/smallrye/smallrye-config/[GitHub project repository]
* https://github.com/eclipse/microprofile-config/[Eclipse MicroProfile Config]
