= Kubernetes ConfigMap ConfigSource Example

In this example, the `FileSystemConfigSource` is used to access a Kubernetes ConfigMap configuration.

== Setup

Since the `FileSystemConfigSource` is implemented in a separate `SmallRyeConfig` module, it requires an additional
dependency in the project that wants to read configuration from Kubernetes ConfigMap.

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>io.smallrye.config</groupId>
    <artifactId>smallrye-config-source-file-system</artifactId>
    <version>{version}</version>
</dependency>
----

== Registration

The `smallrye-config-source-file-system` automatically registers a `FileSystemConfigSourceFactory` that accepts the
configuration property `smallrye.config.source.file.location` to set the volume path and read the Kubernetes ConfigMap.

Usually, an environment variable `SMALLRYE_CONFIG_SOURCE_FILE_LOCATION` sets the ConfigMap location in the Kubernetes
file descriptor.

== Run

The example starts a simple http server with a single endpoint im `/configMap`. To deploy the example in a Kubernetes
cluster requires the following steps.

Set up a local Docker Registry first to store the generated Docker images:

[source,bash]
----
docker run -d -p 5000:5000 --restart=always --name docker-registry registry:2
----

Set up a host in '/etc/hosts' pointing `127.0.0.1` to `docker-registry`.

Build the example with:

[source,bash]
----
mvn package docker:build docker:push
----

Deploy to Kubernetes with:

[source,bash]
----
kubectl apply -f .kubernetes
----

Call tbe endpoint `curl http://localhost:8080/configMap`. This should list all the configurations set in the Kubernets
Config Map. The Kubernetes and ConfigMap configuration can be found in `.kubernetes/configmap-app.yml`.
