= HOCON source config

Implementation of a https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc[MicroProfile ConfigSource] to support https://github.com/lightbend/config/blob/master/HOCON.md[HOCON] file format.

Using the MicroProfile Configuration API is a really convenient way to configure your application.
The standard MicroProfile Configuration Sources are Environment Variables, System Variables and via a microprofile-config.properties file in the Classpath.
This project adds an additional source which reads microprofile-config.conf file in HOCON format.

== Usage

To use the HOCON MicroProfile Config source, add the following to your Maven `pom.xml`

```xml
<dependency>
    <groupId>io.smallrye.config</groupId>
    <artifactId>smallrye-config-source-hocon</artifactId>
    <version>1.6.2-SNAPSHOT</version>
</dependency>
```

This Configuration Source will be looking for the following files in this order of priority:

1. `META-INF/microprofile-config.conf`
2. `WEB-INF/classes/META-INF/microprofile-config.conf`

These configuration files have a lower priority than the default sources.
