name: Publish Docs

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: Tag version to perform release
        type: string

permissions:
  contents: write

jobs:
  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        name: checkout ${{inputs.version}}
        with:
          ref: ${{inputs.version}}

      - name: git author
        run: |
          git config --global user.name "SmallRye CI"
          git config --global user.email "smallrye@googlegroups.com"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: docs release ${{inputs.version}}
        run: |
          cd documentation
          mvn package
          pipx install pipenv
          pipenv install
          git fetch origin gh-pages --depth=1
          pipenv run mike deploy --config-file=mkdocs.yaml --push --update-aliases "${PROJECT_VERSION}" Latest
        env:
          PROJECT_VERSION: ${{inputs.version}}
