name: SmallRye Release
run-name: Perform ${{github.event.inputs.tag || github.ref_name}} Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  attestations: write
  id-token: write
  # Needed for the publish-* workflows
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perform-release:
    name: Perform Release
    uses: smallrye/.github/.github/workflows/perform-release.yml@main
    secrets: inherit
    with:
      version: ${{github.event.inputs.tag || github.ref_name}}

  publish-docs:
    name: Publish Docs
    uses: ./.github/workflows/publish-docs.yml
    secrets: inherit
    with:
      version: ${{github.event.inputs.tag || github.ref_name}}

  publish-tck:
    name: Publish TCK Report
    uses: ./.github/workflows/publish-tck.yml
    secrets: inherit
    with:
      version: ${{github.event.inputs.tag || github.ref_name}}
